[versions]
agp = "8.1.1"
kotlin = "1.8.21"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
